"""add segment text columns to ragas_evaluation new

Revision ID: 34ef5a486031
Revises: e68a30ecd06a
Create Date: 2026-07-03 01:53:43.009443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34ef5a486031'
down_revision: Union[str, Sequence[str], None] = 'e68a30ecd06a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ragas_evaluation', sa.Column('faithfulness_text', sa.Text(), nullable=True))
    op.add_column('ragas_evaluation', sa.Column('answer_qa_text', sa.Text(), nullable=True))
    op.add_column('ragas_evaluation', sa.Column('answer_risk_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ragas_evaluation', 'answer_risk_text')
    op.drop_column('ragas_evaluation', 'answer_qa_text')
    op.drop_column('ragas_evaluation', 'faithfulness_text')
    # ### end Alembic commands ###
