"""fix_7_add_faithfulness_segments_to_ragas_evaluation

Revision ID: 38d6dbb737a1
Revises: 7b2c0b178e88
Create Date: 2026-07-02 23:52:05.497008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38d6dbb737a1'
down_revision: Union[str, Sequence[str], None] = '7b2c0b178e88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ragas_evaluation', sa.Column('faithfulness_summary', sa.Float(), nullable=True))
    op.add_column('ragas_evaluation', sa.Column('faithfulness_qa', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ragas_evaluation', 'faithfulness_qa')
    op.drop_column('ragas_evaluation', 'faithfulness_summary')
    # ### end Alembic commands ###
