"""add rag history table

Revision ID: 4f700b827c23
Revises: 
Create Date: 2026-05-16 22:39:43.545384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f700b827c23'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_base', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('raw_transcribe', sa.Text(), nullable=True),
    sa.Column('repaired_text', sa.Text(), nullable=True),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('retrieved_context', sa.Text(), nullable=True),
    sa.Column('generate_material', sa.Text(), nullable=True),
    sa.Column('compliance_score', sa.Integer(), nullable=True),
    sa.Column('decision_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_history_id'), 'rag_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rag_history_id'), table_name='rag_history')
    op.drop_table('rag_history')
    # ### end Alembic commands ###
