"""add segmented ragas metrics

Revision ID: 6367d08f58ae
Revises: 3272eddd233c
Create Date: 2026-06-06 16:56:22.011289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6367d08f58ae'
down_revision: Union[str, Sequence[str], None] = '3272eddd233c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ragas_evaluation', sa.Column('evaluated_segments', sa.JSON(), nullable=True))
    op.drop_column('ragas_evaluation', 'answer_faithfulness_segment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ragas_evaluation', sa.Column('answer_faithfulness_segment', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('ragas_evaluation', 'evaluated_segments')
    # ### end Alembic commands ###
