"""remove overall and coverage from ragas evaluation

Revision ID: 78610b14b032
Revises: da434c6d8c6f
Create Date: 2026-06-14 22:26:21.035150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78610b14b032'
down_revision: Union[str, Sequence[str], None] = 'da434c6d8c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ragas_evaluation', 'overall_score')
    op.drop_column('ragas_evaluation', 'coverage_pct')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ragas_evaluation', sa.Column('coverage_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('ragas_evaluation', sa.Column('overall_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
