"""add faithfulness_summary, faithfulness_qa, faithfulness_text, answer_risk_text to ragas_evaluation

Revision ID: a0eadfd289f7
Revises: efed3397164b
Create Date: 2026-07-03 02:31:07.024413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0eadfd289f7'
down_revision: Union[str, Sequence[str], None] = 'efed3397164b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ragas_evaluation', 'answer_qa_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ragas_evaluation', sa.Column('answer_qa_text', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
