"""add answer_qa

Revision ID: da434c6d8c6f
Revises: d9e012aabb71
Create Date: 2026-06-06 18:15:26.697383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da434c6d8c6f'
down_revision: Union[str, Sequence[str], None] = 'd9e012aabb71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ragas_evaluation', sa.Column('answer_qa', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ragas_evaluation', 'answer_qa')
    # ### end Alembic commands ###
