"""add segment text columns to ragas_evaluation

Revision ID: e68a30ecd06a
Revises: 38d6dbb737a1
Create Date: 2026-07-03 01:52:46.747481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e68a30ecd06a'
down_revision: Union[str, Sequence[str], None] = '38d6dbb737a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
