"""initial_new_structured_rag_architecture

Revision ID: ed204709bcd2
Revises: 
Create Date: 2026-06-03 00:37:09.412691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed204709bcd2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rag_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_title', sa.String(), nullable=True),
    sa.Column('knowledge_base', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_session_id'), 'rag_session', ['id'], unique=False)
    op.create_table('rag_process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('raw_transcribe', sa.Text(), nullable=True),
    sa.Column('repaired_text', sa.Text(), nullable=True),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('retrieved_context', sa.Text(), nullable=True),
    sa.Column('generated_material', sa.Text(), nullable=True),
    sa.Column('compliance_score', sa.Integer(), nullable=True),
    sa.Column('decision_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['rag_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_process_id'), 'rag_process', ['id'], unique=False)
    op.create_index(op.f('ix_rag_process_session_id'), 'rag_process', ['session_id'], unique=False)
    op.create_table('ragas_evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('process_id', sa.Integer(), nullable=False),
    sa.Column('evaluation_type', sa.String(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('ground_truth', sa.Text(), nullable=True),
    sa.Column('faithfulness', sa.Float(), nullable=True),
    sa.Column('answer_relevancy', sa.Float(), nullable=True),
    sa.Column('context_precision', sa.Float(), nullable=True),
    sa.Column('context_recall', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['process_id'], ['rag_process.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ragas_evaluation_id'), 'ragas_evaluation', ['id'], unique=False)
    op.create_index(op.f('ix_ragas_evaluation_process_id'), 'ragas_evaluation', ['process_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ragas_evaluation_process_id'), table_name='ragas_evaluation')
    op.drop_index(op.f('ix_ragas_evaluation_id'), table_name='ragas_evaluation')
    op.drop_table('ragas_evaluation')
    op.drop_index(op.f('ix_rag_process_session_id'), table_name='rag_process')
    op.drop_index(op.f('ix_rag_process_id'), table_name='rag_process')
    op.drop_table('rag_process')
    op.drop_index(op.f('ix_rag_session_id'), table_name='rag_session')
    op.drop_table('rag_session')
    # ### end Alembic commands ###
