"""add faithfulness_text and answer_risk_text to ragas_evaluation

Revision ID: efed3397164b
Revises: 34ef5a486031
Create Date: 2026-07-03 02:00:08.752853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efed3397164b'
down_revision: Union[str, Sequence[str], None] = '34ef5a486031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
